IF (NOT DEFINED MAIN_PROJECT_DIR)
    MESSAGE(FATAL_ERROR "MAIN_PROJECT_DIR IS NOT DEFINED")
ENDIF()

SET(CLANG_FORMAT_COUNTER 0)
ADD_CUSTOM_TARGET(CLANG_FORMAT_TARGET)

MACRO (CREATE_CLANG_FORMAT_TARGET SOURCES_VARIABLE_NAME)
    SET(SOURCES ${${SOURCES_VARIABLE_NAME}})
    SET(TARGET_NAME "CLANG_FORMAT_TARGET${CLANG_FORMAT_COUNTER}")
    MATH(EXPR CLANG_FORMAT_COUNTER "${CLANG_FORMAT_COUNTER} + 1")
    ADD_CUSTOM_TARGET(${TARGET_NAME}
                      COMMAND clang-format "-i" "-style=file" ${SOURCES}
                      WORKING_DIRECTORY ${MAIN_PROJECT_DIR})
    ADD_DEPENDENCIES(CLANG_FORMAT_TARGET ${TARGET_NAME})
ENDMACRO()
