INCLUDE(${MAIN_CMAKE}/Config.cmake)

FILE(GLOB_RECURSE EXECUTABLES ${DEB_EXECUTABLES_DIR}/*)
EXECUTE_PROCESS(
    COMMAND bash ${MAIN_SCRIPTS_DIR}/get_app_dependencies.sh ${EXECUTABLES}
    OUTPUT_VARIABLE EXEC_DEPENDENCIES)
EXECUTE_PROCESS(
    COMMAND bash ${MAIN_SCRIPTS_DIR}/get_directory_size.sh ${DEB_DIR}
    OUTPUT_VARIABLE DEB_PACKAGE_SIZE)

IF (EXEC_DEPENDENCIES STREQUAL "")
    MESSAGE(FATAL_ERROR "NOOO")
ENDIF()

STRING (REPLACE "\n" "" EXEC_DEPENDENCIES ${EXEC_DEPENDENCIES})
STRING (REPLACE "\n" "" DEB_PACKAGE_SIZE ${DEB_PACKAGE_SIZE})

SET (DEB_DEPENDENCIES ${EXEC_DEPENDENCIES})
SET (DEB_APP_SIZE ${DEB_PACKAGE_SIZE})

CONFIGURE_FILE(${MAIN_TEMPLATES_DIR}/deb_package/control.in ${DEB_CONTROL_PATH}/control)
