IF (NOT DEFINED MAIN_PROJECT_DIR)
    MESSAGE(FATAL_ERROR "MAIN_PROJECT_DIR IS NOT DEFINED")
ENDIF()

set(WAV_ASSETS_DIR ${MAIN_PROJECT_DIR}/assets/wav) 

FUNCTION (WAV_ASSETS_TO_SOURCES SOURCES_GENERATED OUTPUT_DIR)
    FILE(GLOB_RECURSE ASSETS RELATIVE "${WAV_ASSETS_DIR}" "${WAV_ASSETS_DIR}/*")

    SET(ASSETS_COPY_DIR ${OUTPUT_DIR}/assets_wav)
    SET(ASSETS_GENERATED_DIR ${OUTPUT_DIR}/generated_wav)

    FILE(MAKE_DIRECTORY ${ASSETS_COPY_DIR})
    FILE(MAKE_DIRECTORY ${ASSETS_GENERATED_DIR})

    SET(OUTPUT_FILENAMES)
    FOREACH(ASSET ${ASSETS})
        SET(ASSET_ABS_PATH "${WAV_ASSETS_DIR}/${ASSET}")
        SET(ASSET_COPY_ABS_PATH "${ASSETS_COPY_DIR}/${ASSET}")
        STRING(REPLACE ".wav" ".cpp" OUTPUT_NAME ${ASSET})
        STRING(REPLACE "/" "_" OUTPUT_FLAT_NAME ${OUTPUT_NAME})
        SET(ASSET_GENERATED_ABS_NAME "${ASSETS_GENERATED_DIR}/${OUTPUT_FLAT_NAME}")

        ADD_CUSTOM_COMMAND(OUTPUT ${ASSET_GENERATED_ABS_NAME}
                           COMMAND ${CMAKE_COMMAND} -E copy ${ASSET_ABS_PATH} ${ASSET_COPY_ABS_PATH}
                           COMMAND xxd "-i" ${ASSET} > ${ASSET_GENERATED_ABS_NAME}
                           WORKING_DIRECTORY ${WAV_ASSETS_DIR})
        LIST(APPEND OUTPUT_FILENAMES ${ASSET_GENERATED_ABS_NAME})
    ENDFOREACH(ASSET ${ASSETS})
    
    SET(${SOURCES_GENERATED} ${OUTPUT_FILENAMES} PARENT_SCOPE)
ENDFUNCTION()