
MACRO (CONFIG_DEFINE_VARIABLES)
    
    SET (DEB_VERSION           0.4-alpha          )
    SET (DEB_MAINTAINER_NAME   zhekehz            )
    SET (DEB_MAINTAINER_EMAIL  zzzheka97@gmail.com)

    SET (GEXT_VERSION          0.4                )

ENDMACRO()

MACRO (CONFIG_EVAL_VARIABLES)

    STRING(REPLACE "@" "." _DEB_MAINTAINER_EMAIL ${DEB_MAINTAINER_EMAIL})
    SET (GNOME_EXTENSION_NAME typewriter-kb@${_DEB_MAINTAINER_EMAIL})

ENDMACRO()

CONFIG_DEFINE_VARIABLES()
CONFIG_EVAL_VARIABLES()